name: future_gate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: ^2.12.0  # متوافق مع flutter_test
  fake_async: 1.3.2  # متوافق مع flutter_test
  leak_tracker: ^10.0.8
  leak_tracker_testing: 3.0.1  # متوافقة مع flutter_test
  vm_service: 14.3.1  # متوافقة مع flutter_test
  material_color_utilities: 0.11.1  # متوافقة مع flutter_test
  vector_math: 2.1.4  # متوافقة مع flutter_test

flutter:
  uses-material-design: true
  assets:
    - assets/images/
